draw_sprite_ext(sprite_index, image_index, x - 1, y - 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x - 1, y + 0, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x - 1, y + 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 0, y - 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 0, y + 0, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 0, y + 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 1, y - 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 1, y + 0, image_xscale, image_yscale, image_angle, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 1, y + 1, image_xscale, image_yscale, image_angle, c_black, 1);
draw_self();